apiVersion: v1
kind: Namespace 
metadata:
  name: frontend
  label: 
    namespace: frontend

---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx
spec:
  namespace: frontend 
  containers: 
    - name: nginx
      image: docker.io/nginx