apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: frontendreplica
  labels:
    app: nginx
spec: # spec of replica set
  replicas: 3
  selector: 
    matchLabels: 
     app: nginx
  template: #pod template
    metadata:
      labels:
        app: nginx
    spec:  # spec for container
     containers:
      - name: nginx
        image: docker.io/nginx
# multiple files use ---