apiVersion:

---
apiVersion: v1
kind: ReplicaSet
metadata: 
  name: replicaset01
  labels:
    app: nginx
  # annotations:
  #   controller.kubernetes.io/pod-deletion-cost: "10"
spec: # spec of replica set
  replicas: 3
  selector: 
    matchLabels: 
     app: nginx
  template: #pod template
    metadata:
      labels:
        app: nginx
    spec:  # spec for container
     containers:
      - name: nginx
        image: docker.io/nginx
# multiple files use ---
---