apiVersion: v1 
kind: Secret 
metadata:
  name: secret-07-1
data: 
  password: asdsd456 # always convert base 64 no use any one can decode

---
apiVersion: v1 
kind: Pod
metadata: 
  name: pod-07-secret
spec: 
  containers:
    - name: debug
      image: docker.io/rkalluru/debug
      env: 
       - name: password
         valueFrom: 
           secretKeyRef: 
             name:  secret-07-1
             key: password