---
apiVersion: v1 
kind: ServiceAccount
metadata:
  name: debug
  namespace: default

---
apiVersion: v1 
kind: Pod
metadata: 
  name: debug
  namespace: default
spec: 
  serviceAccountName: debug
  containers:
    - name: debug
      image: docker.io/rkalluru/debug

---
# before  above Pods doenst have autorization, write rule for pod using Role
apiVersion: rbac.authorization.k8s.io/v1 
kind: Role # role creation- need to associate /bind #role has access to only that namespaces
metadata: 
  namespace: default 
  name: default-ns-pod-reader
rules: 
 - apiGroups: [""]
   resources: ["pods"]
   verbs: ["get","watch","list"]

---
# role binding
apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding
metadata: 
  name: default-ns-pod-reader-to-debug-sa
  namespace: default
roleRef: 
  kind: Role
  name: default-ns-pod-reader 
  apiGroup: rbac.authorization.k8s.io
subjects: 
  - kind: ServiceAccount 
    name: debug
    namespace: default

# create namespace test cluster role can give to multi namespace
#kubectl create ns test
# get one more namespce access to pod
---
apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding
metadata: 
  name: kube-system-ns-pod-reader-to-debug-sa
  namespace: kube-system
roleRef: 
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects: 
  - kind: ServiceAccount 
    name: debug
    namespace: default