apiVersion: v1
kind: Service
metadata:
  name: quiz-app-service
spec:
  selector:
    app: quiz-app
  type: NodePort
  ports:
  - port: 2500           # Exposed port on the service
    targetPort: 2500     # Pod's container port
    #nodePort: 30001      # Node's port (optional; Kubernetes assigns one if omitted)
