apiVersion: v1
kind: Service
metadata:
  name: quiz-app-service
spec:
  selector:
    app: quiz-app
  type: LoadBalancer
  ports:
  - port: 2500           # Exposed port on the service
    targetPort: 2500     # Pod's container port
