--- 
apiVersion: v1 
kind: Pod 
metadata:  
  name: nginx 
  labels: 
    appName: nginx 
spec: 
  containers: 
    - name: nginx 
      image: nginx 
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: nginx 
spec:  
  selector: 
     appName: nginx 
     example: service 
  ports:  
    - protocol: TCP 
      port: 80 
      targetPort: 80 
---
apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  name: nginx 
  annotations: 
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:633788536644:certificate/764c1d94-5562-48f4-be92-fca22568f53d
    alb.ingress.kubernetes.io/group.name: roboshop 
    alb.ingress.kubernetes.io/healthcheck-path: / 
    alb.ingress.kibernetes.io/scheme: internet-facing
spec: 
  ingressClassName: alb 
  rules: 
   - host: nginx-test.manupanand.online 
     http: 
       paths: 
         - backend: 
             service: 
                name: nginx 
                port: 
                  number: 80
           path: /
           pathType: Prefix

--- 
apiVersion: security.istio.io/v1beta1 
kind: PeerAuthentication 
metadata: 
   name:  default 
spec: 
  mtls:  
    mode: STRICT #enforcing mtls for all service in namespace
---
# allowing everyone for pod name nginx 
apiVersion: security.istio.io/v1 
kind: AuthorizationPolicy 
metadata: 
  name:  nginx 
spec: 
  selector: 
    matchLabels:  
      appName: nginx 
  action: ALLOW 
  rules: 
    - {}

---
# on frontend when istio is present it was not loading, istio disabled it will load
# add istio gateway also
apiVersion: networking.istio.io/v1aplha3
kind: Gateway 
metadata: 
  name: nginx 
spec: 
  selector: 
    istio: ingressgateway 
  servers: 
  - port: 
      number: 80 
      name: http
      protocol: HTTP 
    host: 
     - "*"
---
apiVersion: networking.istio.io/v1aplha3
kind: VirtualService
metadata: 
  name: nginx 
spec: 
  hosts: 
   - "*" 
  gateways: 
  - nginx 
  http: 
  - match: 
    - uri: 
        exact: /
    route: 
    - destination: 
        host: nginx 
        port: 
          number: 80 
 
#check vide 4 nov 94