apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80 #internal
      targetPort: 80  #container
      nodePort: 30007  # This port can be any valid port within the NodePort range
  type: NodePort