apiVersion: v1 
kind: Pod 
metadata: 
  name: sample
spec: 
  containers: 
    - name: debug
      image: docker.io/rkalluru/debug
      env: 
        - name: CATALOGUE_HOST
          value: "test env"

---
# kubectl get pods
# kubectl exec -it podname -- env  to see environment variables 

# instead use config to manage have centralised way to use configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-01
data:
  CATALOGUE_HOST: "catalogue"
  CART_HOST: "cart"

--- 
apiVersion: v1 
kind: Pod 
metadata: 
  name: sample
spec: 
  containers: 
    - name: debug
      image: docker.io/rkalluru/debug
      env: 
        - name: CATALOGUE_HOST
          valueFrom: 
            configMapKeyRef: 
              name: cm-01 
              key: CATALOGUE_HOST
        - name: CART_HOST_HOST
          valueFrom: 
            configMapKeyRef: 
              name: cm-01 
              key: CART_HOST_HOST
