apiVersion: v1 
kind: Pod 
metadata: 
  name: sample
spec: 
  containers: 
    - name: debug
      image: docker.io/rkalluru/debug
      env: 
        - name: CATALOGUE_HOST
          value: "test env"

---
# kubectl get pods
# kubectl exec -it podname -- env  to see environment variables 

# instead use config to manage have centralised way to use configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-07-file
data:
  catalogue.service: |
    [Unit] 
    Description = Catalogue.service 
    
    [Service]
    User=roboshop
    Environemnt=Mongo
    ExecStart=/bin/node /app/server.js

    [Install]
    WantedBy=multi-user.target

--- 
apiVersion: v1 
kind: Pod 
metadata: 
  name: sample-cm1-file
spec: 
  containers: 
    - name: debug
      image: docker.io/rkalluru/debug
      volumeMounts: 
        - name: config-volume 
          mountPath: /etc/config 
  volumes: 
    - name: config-volume 
      configMap: 
         name: cm-07-file
# also can mount config map as file and use it

--- 
# secret creation - in base64 format
apiVersion: v1
kind: Secret
metadata:
  name: secret-07-1
data:
  password: abcd  #base64 converted

--- 
apiVersion: v1 
kind: Pod 
metadata: 
  name: sample-cm1-file
spec: 
  containers: 
    - name: debug
      image: docker.io/rkalluru/debug
      env: 
        - name: password 
          valueFrom: 
            secretKeyRef: 
              name: secret-07-1 
              key: password