apiVersion: v1 
kind: ServiceAccount
metadata: 
  name: debug
  namespace: default

---
apiVersion: v1
kind: Pod 
metadata: 
   name: debug 
   namespace: default 
spec: 
  serviceAccountName: debug
  containers:  
     - name: debug 
       image: docker.io/rkalluru/debug

# kubectl get sa - for service accounts
---
apiVersion: rbac.authorization.k8s.io/v1 
kind: Role # like role policy attachment in iam
metadata:  
  namespace: default 
  name: default-ns-pod-reader
rules: 
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding  # like role in iam
metadata:  
  name: default-ns-pod-reader-to-debug-sa 
  namespace: default 
subjects:  
  - kind: ServiceAccount
    name: debug
    namespace: default
roleRef: 
   kind: Role 
   name: pod-reader 
   apiGroup: rbac.authorization.k8s.io 
--- # creating a cluster role |get one more acess for debug pod - kube-system namespace
apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding  # like role in iam
metadata:  
  name: default-ns-pod-reader-to-debug-sa 
  namespace: kube-system
subjects:  
  - kind: ServiceAccount
    name: debug
    namespace: default
roleRef: 
   kind: ClusterRole
   name: view
   apiGroup: rbac.authorization.k8s.io 