apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-01 # name of replica
  labels:
    app: nginx
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:  
      app: nginx
          # matches the lable on pod created by replicasets 
    #| ensure replicaset understand which Pod belong to it 
    #|must match the label in template.metadata, otherwise replicset wont manage it
  template:
    # this is pod template- blue print of Pods that replicaset should create
    metadata:
      labels: # labels must match seletor.matchLabels
        app: nginx
    spec: # actual spec of Pod
      containers:
      - name: nginx
        image: docker.io/nginx
