apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore 
metadata: 
    name: vault-backend  
spec: 
    provider: 
        vault: 
          server: "http://vault-public.manupanand.online:8200"  
          path: "roboshop-k8s"
          version: "v2"  
          auth: 
            tokenSecretRef: 
              name: "vault-token"
              key: "token" 
              namespace: kube-system