
apiVersion: v1 #way to create secret in k8s
kind: Secret 
metadata: 
  name: vault-token 
data: 
  token: # base 64 token

---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore 
metadata: 
  name: vault-backend  #name of store
spec: 
  provider: 
    vault: 
      server: "http://vault-public.manupanand.online:8200" # tls cert and key removed 
      path: "roboshop-k8s"
      version: "v2"  # copy tsl.crt ,tls.key
      auth: 
        tokenSecretRef: 
           name: "vault-token"
           key: "token" 
--- 
#fetch secret her
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret 
# metadata: 
#   name: vault-example
# spec: 
#   refreshInterval: "15s"
#   secretStoreRef: # above created store refernce
#     name: vault-backend 
#     kind: SecretStore 
#   target: 
#     name:  cart # here write secret name from vault to be matched here
#   data:  # we are copying from vault and creting in k8s here
#    - extract: 
#        key: cart
       
# above is ectracting many thing
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-example
spec:
  refreshInterval: "15s"
  secretStoreRef: # above created store refernce
    name: vault-backend
    kind: SecretStore
  target:
    name:  cart # here write secret name from vault to be matched here
  dataFrom:  # we are copying from vault and creting in k8s here
   - extract:
       key: cart
