
apiVersion: v1 #way to create secret in k8s
kind: Secret 
metadata: 
  name: vault-token 
data: 
  token: # base 64 token
  tls.key: #paste here
  tls.crt: #paste here
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore 
metadata: 
  name: vault-backend 
spec: 
  provider: 
    vault: 
      server: "https://vault-public.manupanand.online:8200"
      path: "roboshop-k8s"
      version: "v2"  # copy tsl.crt ,tls.key
      tls: 
        clientCert: 
           name: "vault-token"
           key: "tls.crt"
        secretRef: 
           name: "vault-token"
           key: "tls.key"

      auth: 
        tokenSecretRef: 
           name: "vault-token"
           key: "token" 
--- 