# kubectl create secret generic vault-token \
#   --from-literal=token=YOUR_VAULT_TOKEN \
#   -n roboshop
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: http://vault.YOUR_DOMAIN:8200
      path: roboshop-k8s
      version: v2
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          namespace: roboshop  # 👈 VERY IMPORTANT
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
  namespace: roboshop   # 👈 The app namespace
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cart
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: cart
