---
apiVersion: batch/v1
kind: Job 
metadata: 
  name: catalogue-schema
  namespace: roboshop 
  labels: 
    appName: catalogue
spec:  
  template: 
    spec:  
      containers:  
        - name: catalogue 
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          env: 
            - name: DB_TYPE
              value: "mongo"
            - name: APP_GIT_URL 
              value: "https://github.com/roboshop-devops-project-v3/catalogue"
            - name: DB_HOST 
              value: "mongo.subnet_name_c.manupanand.online"
            - name: SCHEMA_FILES
              value: "db/master-data.js"
      restartPolicy: Never 
  backoffLimit: 0
---
---
# job continer will terminate after completion of job

apiVersion: batch/v1
kind: Job 
metadata: 
  name: shipping-schema
  namespace: roboshop 
  labels: 
    appName: shipping
spec:  
  backoffLimit: 0
  template: 
    spec:  
      restartPolicy: Never 
      containers:  # make containers for each load
        # - name: app-user
        #   image: docker.io/manupanand/schema:latest 
        #   env: 
        #     - name: DB_TYPE
        #       value: "mysql"
        #     - name: APP_GIT_URL 
        #       value: "https://github.com/manupanand-freelance-developer/schema-load"
        #     - name: DB_HOST 
        #       value: "mysql.subnet_name_c.db.manupanand.online" 
        #     - name: DB_USER
        #       value: "shipping"
        #     - name: DB_PASS 
        #       value: Roboshop@1
        #     - name: SCHEMA_FILES # s
        #       value: db/app-user.sql 
        - name: schema
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load 
          env: 
            - name: DB_TYPE
              value: "mysql"
            - name: APP_GIT_URL 
              value: "https://github.com/roboshop-devops-project-v3/shipping"
            - name: REPO_DIR
              value: "schema-load"
            - name: DB_HOST
              value: "mysql.subnet_name_c.manupanand.online"  # Use environment variable or fallback to localhost
            - name: DB_USER
              value: "shipping"
            - name: DB_PASS
              value: "Roboshop@1"

              # export DB_TYPE=mysql; export APP_GIT_URL="https://github.com/manupanand-freelance-developer/schema-load"; export REPO_DIR="schema-load"; export DB_HOST="mysql.subnet_name_c.manupanand.online"; export DB_USER="shipping"; export  DB_PASS="Roboshop@1"



   