apiVersion: external-secrets.io/v1
kind: ExternalSecret 
metadata: 
  name: {{ .Values.name }}
  namespace: roboshop
  annotations: 
    helm.sh/hook: pre-install #helm hook
spec:  
  refreshInterval: "15s"
  secretStoreRef: 
    name: vault-backend 
    kind: ClusterSecretStore 
  target: 
    name: {{ .Values.name }}
  dataFrom:  
    - extract: 
       key: {{ .Values.name }}