apiVersion: v1 
kind: Service 
metadata:  
  name: {{ .Values.name }}
  namespace: roboshop 
spec: 
  type: {{ .Values.serviceType }} # only for frontend loadBalancer
  selector: 
    appName:  {{ .Values.name }}
  ports: 
    - protocol: TCP 
      port: {{ .Values.sport }}
      targetPort: {{ .Values.port }}