apiVersion: v1 
kind: Service
metadata: 
  name: cart-service
  namespace: roboshop
spec:
  type: ClusterIP  
  selector: 
    appName: cart
  ports: 
    - protocol: TCP 
      port: 8080
      targetPort: 8080