apiVersion: v1 
kind: Service
metadata: 
  name: frontend-service
spec: 
  type: LoadBalancer
  selector: 
    appName: frontend
  ports: 
    - protocol: TCP 
      port: 80 
      targetPort: 80 
---
apiVersion: v1 
kind: Service
metadata: 
  name: catalogue-service
spec:
  type: ClusterIP  
  selector: 
    appName: catalogue
  ports: 
    - protocol: TCP 
      port: 8080
      targetPort: 8080
---

apiVersion: v1 
kind: Service
metadata: 
  name: user-service
spec:
  type: ClusterIP  
  selector: 
    appName: user
  ports: 
    - protocol: TCP 
      port: 8080
      targetPort: 8080
---

apiVersion: v1 
kind: Service
metadata: 
  name: cart-service
spec:
  type: ClusterIP  
  selector: 
    appName: cart
  ports: 
    - protocol: TCP 
      port: 8080
      targetPort: 8080
---

apiVersion: v1 
kind: Service
metadata: 
  name: shipping-service
spec:
  type: ClusterIP  
  selector: 
    appName: shipping
  ports: 
    - protocol: TCP 
      port: 8080
      targetPort: 8080
---

apiVersion: v1 
kind: Service
metadata: 
  name: payment-service
spec:
  type: ClusterIP  
  selector: 
    appName: payment
  ports: 
    - protocol: TCP 
      port: 8080
      targetPort: 8080
--- 

apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: roboshop
  labels:
    appName: frontend
spec:
  containers:
    - name: frontend
      image: docker.io/manupanand/ecomm-frontend:latest
      env:
        - name: CATALOGUE_HOST
          value: "catalogue-service"
        - name: CATALOGUE_PORT
          value: "8080"
        - name: USER_HOST
          value: "user-service"
        - name: USER_PORT
          value: "8080"
        - name: CART_HOST
          value: "cart-service"
        - name: CART_PORT
          value: "8080"
        - name: SHIPPING_HOST
          value: "shipping-service"
        - name: SHIPPING_PORT
          value: "8080"
        - name: PAYMENT_HOST
          value: "payment-service"
        - name: PAYMENT_PORT
          value: "8080"
