apiVersion: v1 
kind: Service
metadata: 
  name: frontend
spec: 
  type: LoadBalancer
  selector: 
    appName: frontend
  ports: 
    - protocol: TCP 
      port: 80 
      targetPort: 80 
---
apiVersion: v1 
kind: Service
metadata: 
  name: catalogue
spec: 
  selector: 
    appName: catalogue
  ports: 
    - protocol: TCP 
      port: 8080
      targetPort: 8080
---