apiVersion: v1 
kind: Service
metadata: 
  name: frontend-service
spec: 
  type: LoadBalancer
  selector: 
    appName: frontend
  ports: 
    - protocol: TCP 
      port: 80 
      targetPort: 80 
---
apiVersion: v1 
kind: Service
metadata: 
  name: catalogue-service
spec:
  type: ClusterIP  
  selector: 
    appName: catalogue
  ports: 
    - protocol: TCP 
      port: 8080
      targetPort: 8080
---

apiVersion: v1 
kind: Service
metadata: 
  name: user-service
spec:
  type: ClusterIP  
  selector: 
    appName: user
  ports: 
    - protocol: TCP 
      port: 8080
      targetPort: 8080
---

apiVersion: v1 
kind: Service
metadata: 
  name: cart-service
spec:
  type: ClusterIP  
  selector: 
    appName: cart
  ports: 
    - protocol: TCP 
      port: 8080
      targetPort: 8080
---

apiVersion: v1 
kind: Service
metadata: 
  name: shipping-service
spec:
  type: ClusterIP  
  selector: 
    appName: shipping
  ports: 
    - protocol: TCP 
      port: 8080
      targetPort: 8080
---

apiVersion: v1 
kind: Service
metadata: 
  name: payment-service
spec:
  type: ClusterIP  
  selector: 
    appName: payment
  ports: 
    - protocol: TCP 
      port: 8080
      targetPort: 8080
---