apiVersion: v1 
kind: Service
metadata: 
  name: payment-service
  namespace: roboshop
spec:
  type: ClusterIP  
  selector: 
    appName: payment
  ports: 
    - protocol: TCP 
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment 
  namespace: roboshop 
  labels: 
    appName: payment
spec:
  replicas: 1
  selector:
    matchLabels:
     appName: payment
  template:
    metadata:
      labels:
       appName: payment
    spec:
      containers:
      - name: payment
        image: docker.io/manupanand/ecomm-payment:latest
        env: 
          - name: CART_HOST 
            value: "cart-service" 
          - name: CART_PORT 
            value: "8080"
          - name: USER_HOST 
            value: "user-service"
          - name: USER_PORT 
            value: "8080"
          - name: AMQP_HOST
            value: "rabbitmq.subnet_name_c.db.manupanand.online"
          - name: AMQP_USER 
            value: roboshop 
          - name: AMQP_PASS 
            value: "roboshop123"