apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  namespace: roboshop
spec:
  type: {{.Values.serviceType}}  # only for frontend Loadbalancer
  selector:
    appName: {{.Values.name}}
  ports: 
    - protocol: TCP
      port: {{.Values.port}}
      targetPort: {{.Values.port}}